services:
  php:
    container_name: ${PROJECT}_php
    image: ${PROJECT}_php:${TAG}
    build:
      context: .
      dockerfile: docker/dev/php/Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/site
    networks:
      - appnet

  nginx:
    container_name: ${PROJECT}_nginx
    image: ${PROJECT}_nginx:${TAG}
    build:
      context: .
      dockerfile: docker/dev/nginx/Dockerfile
    ports:
      - 94:80
    depends_on:
      - php
    volumes:
      - './src:/site'
    networks:
      - appnet

  db:
    image: postgres:15-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./data/dev/db:/var/lib/postgresql/data:rw
    container_name: ${PROJECT}_db
    hostname: db
    ports:
    - 3334:5432
    networks:
      - appnet

  redis:
    build:
      context: .
      dockerfile: docker/prod/redis/Dockerfile
    container_name: ${PROJECT}_redis
    image: ${PROJECT}_redis:${TAG}
    hostname: redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - ./data/prod/redis:/root/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
#      - REDIS_DATABASES=16
    networks:
      - appnet

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8887:8080"
    container_name: ${PROJECT}_adminer
    hostname: adminer
    networks:
      - appnet
      
#------------

networks:
  appnet:
    name: aspnet
    driver: bridge
    external: true
      
